souffle: souffle::InterpreterNode Class Reference
souffle::InterpreterNode Class Reference
This is a shadow node for a RamNode that is enriched for with local information so that the interpreter is executing quickly.
#include <InterpreterNode.h>
Public Member Functions
const InterpreterNode * getChild (std::size_t i) const
get children of node
const std::vector< std::unique_ptr< InterpreterNode > > & getChildren () const
get list of all children
size_t getData (std::size_t i) const
get data
InterpreterPreamble * getPreamble () const
get preamble
InterpreterRelation * getRelation () const
get relation from handle
const RamNode * getShadow () const
get shadow node, i.e., RAM node
enum InterpreterNodeType getType () const
get node type
InterpreterNode (enum InterpreterNodeType ty, const RamNode *sdw, std::vector< std::unique_ptr< InterpreterNode >> chlds={}, RelationHandle *relHandle=nullptr, std::vector< size_t > data={})
void setPreamble (const std::shared_ptr< InterpreterPreamble > &p)
set preamble
Protected Attributes
std::vector< std::unique_ptr< InterpreterNode > > children
std::vector< size_t > data
std::shared_ptr< InterpreterPreamble > preamble = nullptr
RelationHandle *const relHandle
const RamNode * shadow
enum InterpreterNodeType type
Private Types
using RelationHandle = std::unique_ptr< InterpreterRelation >
Detailed Description
This is a shadow node for a RamNode that is enriched for with local information so that the interpreter is executing quickly.
Definition at line 95 of file InterpreterNode.h.
Member Typedef Documentation
RelationHandle
using souffle::InterpreterNode::RelationHandle = std::unique_ptr<InterpreterRelation> private
Definition at line 96 of file InterpreterNode.h.
Constructor & Destructor Documentation
InterpreterNode()
souffle::InterpreterNode::InterpreterNode (enum InterpreterNodeType ty, const RamNode * sdw, std::vector< std::unique_ptr< InterpreterNode >> chlds = {}, RelationHandle * relHandle = nullptr, std::vector< size_t > data = {}) inline
Definition at line 99 of file InterpreterNode.h.
References children, data, relHandle, shadow, and type.
                                                               {}, RelationHandle* relHandle = nullptr,
             std::vector<size_t> data = {})
             : type(ty), shadow(sdw), children(std::move(chlds)), relHandle(relHandle), data(std::move(data)) {
     }
Member Function Documentation
getChild()
const InterpreterNode* souffle::InterpreterNode::getChild (std::size_t i) const inline
get children of node
Definition at line 116 of file InterpreterNode.h.
References children, and i.
Referenced by souffle::InterpreterEngine::execute().
{
         return children[i].get();
     }
getChildren()
const std::vector<std::unique_ptr<InterpreterNode> >& souffle::InterpreterNode::getChildren () const inline
get list of all children
Definition at line 136 of file InterpreterNode.h.
References children.
Referenced by souffle::InterpreterEngine::execute().
{
         return children;
     }
getData()
size_t souffle::InterpreterNode::getData (std::size_t i) const inline
get data
Definition at line 121 of file InterpreterNode.h.
References i.
Referenced by souffle::InterpreterEngine::execute().
{
         return data[i];
     }
getPreamble()
InterpreterPreamble* souffle::InterpreterNode::getPreamble () const inline
get preamble
Definition at line 126 of file InterpreterNode.h.
References preamble.
Referenced by souffle::InterpreterEngine::execute().
{
         return preamble.get();
     }
getRelation()
InterpreterRelation* souffle::InterpreterNode::getRelation () const inline
get relation from handle
Definition at line 141 of file InterpreterNode.h.
Referenced by souffle::InterpreterEngine::execute().
{
         assert(relHandle && "No relation cached\n");
         return (*relHandle).get();
     }
getShadow()
const RamNode* souffle::InterpreterNode::getShadow () const inline
get shadow node, i.e., RAM node
Definition at line 111 of file InterpreterNode.h.
References shadow.
{
         return shadow;
     }
getType()
enum InterpreterNodeType souffle::InterpreterNode::getType () const inline
get node type
Definition at line 106 of file InterpreterNode.h.
References type.
Referenced by souffle::InterpreterEngine::execute().
{
         return type;
     }
setPreamble()
void souffle::InterpreterNode::setPreamble (const std::shared_ptr< InterpreterPreamble > & p) inline
set preamble
Definition at line 131 of file InterpreterNode.h.
References p, and preamble.
{
         preamble = p;
     }
Field Documentation
children
std::vector<std::unique_ptr<InterpreterNode> > souffle::InterpreterNode::children protected
Definition at line 149 of file InterpreterNode.h.
Referenced by getChild(), getChildren(), and InterpreterNode().
data
std::vector<size_t> souffle::InterpreterNode::data protected
Definition at line 151 of file InterpreterNode.h.
Referenced by InterpreterNode().
preamble
std::shared_ptr<InterpreterPreamble> souffle::InterpreterNode::preamble = nullptr protected
Definition at line 152 of file InterpreterNode.h.
Referenced by getPreamble(), and setPreamble().
relHandle
RelationHandle* const souffle::InterpreterNode::relHandle protected
Definition at line 150 of file InterpreterNode.h.
Referenced by InterpreterNode().
shadow
const RamNode* souffle::InterpreterNode::shadow protected
Definition at line 148 of file InterpreterNode.h.
Referenced by getShadow(), and InterpreterNode().
type
enum InterpreterNodeType souffle::InterpreterNode::type protected
Definition at line 147 of file InterpreterNode.h.
Referenced by getType(), and InterpreterNode().
The documentation for this class was generated from the following file:
InterpreterNode.h