souffle: souffle::RedundantRelations Class Reference
souffle::RedundantRelations Class Reference
Analysis pass identifying relations which do not contribute to the computation of the output relations.
#include <PrecedenceGraph.h>
Public Member Functions
const std::set< const AstRelation * > & getRedundantRelations () const
void print (std::ostream &os) const override
print the analysis result in HTML format
RedundantRelations ()
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "redundant-relations"
Private Attributes
PrecedenceGraph * precedenceGraph = nullptr
std::set< const AstRelation * > redundantRelations
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass identifying relations which do not contribute to the computation of the output relations.
Definition at line 70 of file PrecedenceGraph.h.
Constructor & Destructor Documentation
RedundantRelations()
souffle::RedundantRelations::RedundantRelations () inline
Definition at line 74 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::print(), and souffle::PrecedenceGraph::run().
 : AstAnalysis(name) {}
Member Function Documentation
getRedundantRelations()
const std::set<const AstRelation*>& souffle::RedundantRelations::getRedundantRelations () const inline
Definition at line 80 of file PrecedenceGraph.h.
Referenced by souffle::RemoveRedundantRelationsTransformer::transform().
{
         return redundantRelations;
     }
print()
void souffle::RedundantRelations::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 192 of file PrecedenceGraph.cpp.
{
     os << redundantRelations << std::endl;
 }
run()
void souffle::RedundantRelations::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 151 of file PrecedenceGraph.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and relations.
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraph>();
     std::set<const AstRelation*> work;
     std::set<const AstRelation*> notRedundant;
     auto* ioType = translationUnit.getAnalysis<IOType>();
     const std::vector<AstRelation*>& relations = translationUnit.getProgram()->getRelations();
     /* Add all output relations to the work set */
     for (const AstRelation* r : relations) {
         if (ioType->isOutput(r)) {
             work.insert(r);
         }
     }
     /* Find all relations which are not redundant for the computations of the
        output relations. */
     while (!work.empty()) {
         /* Chose one element in the work set and add it to notRedundant */
         const AstRelation* u = *(work.begin());
         work.erase(work.begin());
         notRedundant.insert(u);
         /* Find all predecessors of u and add them to the worklist
             if they are not in the set notRedundant */
         for (const AstRelation* predecessor : precedenceGraph->graph().predecessors(u)) {
             if (notRedundant.count(predecessor) == 0u) {
                 work.insert(predecessor);
             }
         }
     }
     /* All remaining relations are redundant. */
     redundantRelations.clear();
     for (const AstRelation* r : relations) {
         if (notRedundant.count(r) == 0u) {
             redundantRelations.insert(r);
         }
     }
 }
Field Documentation
name
constexpr const char* souffle::RedundantRelations::name = "redundant-relations" static
Definition at line 72 of file PrecedenceGraph.h.
precedenceGraph
PrecedenceGraph* souffle::RedundantRelations::precedenceGraph = nullptr private
Definition at line 85 of file PrecedenceGraph.h.
redundantRelations
std::set<const AstRelation*> souffle::RedundantRelations::redundantRelations private
Definition at line 87 of file PrecedenceGraph.h.
The documentation for this class was generated from the following files:
ast/analysis/PrecedenceGraph.h
ast/analysis/PrecedenceGraph.cpp