souffle: souffle::InlineRelationsTransformer Class Reference
souffle::InlineRelationsTransformer Class Reference
Transformation pass to inline marked relations.
#include <AstTransforms.h>
Public Member Functions
InlineRelationsTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to inline marked relations.
Definition at line 355 of file AstTransforms.h.
Member Function Documentation
clone()
InlineRelationsTransformer* souffle::InlineRelationsTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 361 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return new InlineRelationsTransformer();
     }
getName()
std::string souffle::InlineRelationsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 357 of file AstTransforms.h.
{
         return "InlineRelationsTransformer";
     }
transform()
bool souffle::InlineRelationsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 988 of file InlineRelationsTransformer.cpp.
References souffle::AstProgram::addClause(), souffle::containsInlinedAtom(), souffle::getClauses(), souffle::getInlinedClause(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::INLINE, souffle::nameInlinedUnderscores(), souffle::normaliseInlinedHeads(), and souffle::AstProgram::removeClause().
{
     bool changed = false;
     AstProgram& program = *translationUnit.getProgram();
     // Replace constants in the head of inlined clauses with (constrained) variables.
     // This is done to simplify atom unification, particularly when negations are involved.
     normaliseInlinedHeads(program);
     // Remove underscores in inlined atoms in the program to avoid issues during atom unification
     nameInlinedUnderscores(program);
     // Keep trying to inline things until we reach a fixed point.
     // Since we know there are no cyclic dependencies between inlined relations, this will necessarily
     // terminate.
     bool clausesChanged = true;
     while (clausesChanged) {
         std::set<AstClause*> clausesToDelete;
         clausesChanged = false;
         // Go through each relation in the program and check if we need to inline any of its clauses
         for (AstRelation* rel : program.getRelations()) {
             // Skip if the relation is going to be inlined
             if (rel->hasQualifier(RelationQualifier::INLINE)) {
                 continue;
             }
             // Go through the relation's clauses and try inlining them
             for (AstClause* clause : getClauses(program, *rel)) {
                 if (containsInlinedAtom(program, *clause)) {
                     // Generate the inlined versions of this clause - the clause will be replaced by these
                     std::vector<AstClause*> newClauses = getInlinedClause(program, *clause);
                     // Replace the clause with these equivalent versions
                     clausesToDelete.insert(clause);
                     for (AstClause* replacementClause : newClauses) {
                         program.addClause(std::unique_ptr<AstClause>(replacementClause));
                     }
                     // We've changed the program this iteration
                     clausesChanged = true;
                     changed = true;
                 }
             }
         }
         // Delete all clauses that were replaced
         for (const AstClause* clause : clausesToDelete) {
             program.removeClause(clause);
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
ast/transform/AstTransforms.h
ast/transform/InlineRelationsTransformer.cpp