souffle: souffle::AdornedPredicate Class Reference
souffle::AdornedPredicate Class Reference
#include <MagicSet.h>
Public Member Functions
AdornedPredicate (AstQualifiedName name, std::string adornment)
std::string getAdornment () const
AstQualifiedName getQualifiedName () const
~AdornedPredicate ()=default
Private Attributes
std::string adornment
AstQualifiedName predicateName
Friends
bool operator< (const AdornedPredicate &p1, const AdornedPredicate &p2)
std::ostream & operator<< (std::ostream &out, const AdornedPredicate &arg)
Detailed Description
Definition at line 40 of file MagicSet.h.
Constructor & Destructor Documentation
AdornedPredicate()
souffle::AdornedPredicate::AdornedPredicate (AstQualifiedName name, std::string adornment) inline
Definition at line 46 of file MagicSet.h.
References ~AdornedPredicate().
             : predicateName(std::move(name)), adornment(std::move(adornment)) {}
~AdornedPredicate()
souffle::AdornedPredicate::~AdornedPredicate () default
Referenced by AdornedPredicate().
Member Function Documentation
getAdornment()
std::string souffle::AdornedPredicate::getAdornment () const inline
Definition at line 55 of file MagicSet.h.
References adornment.
Referenced by souffle::Adornment::run().
{
         return adornment;
     }
getQualifiedName()
AstQualifiedName souffle::AdornedPredicate::getQualifiedName () const inline
Definition at line 51 of file MagicSet.h.
References predicateName.
Referenced by souffle::Adornment::run().
{
         return predicateName;
     }
Friends And Related Function Documentation
operator<
bool operator< (const AdornedPredicate & p1, const AdornedPredicate & p2) friend
Definition at line 64 of file MagicSet.h.
{
         if (p1.getQualifiedName() != p2.getQualifiedName()) {
             return p1.getQualifiedName() < p2.getQualifiedName();
         } else {
             return p1.getAdornment() < p2.getAdornment();
         }
     }
operator<<
std::ostream& operator<< (std::ostream & out, const AdornedPredicate & arg) friend
Definition at line 59 of file MagicSet.h.
{
         out << "(" << arg.predicateName << ", " << arg.adornment << ")";
         return out;
     }
Field Documentation
adornment
std::string souffle::AdornedPredicate::adornment private
Definition at line 43 of file MagicSet.h.
Referenced by getAdornment().
predicateName
AstQualifiedName souffle::AdornedPredicate::predicateName private
Definition at line 42 of file MagicSet.h.
Referenced by getQualifiedName().
The documentation for this class was generated from the following file:
ast/transform/MagicSet.h