souffle: souffle::AstComponent Class Reference
souffle::AstComponent Class Reference
A AST node describing a component within the input program.
#include <AstComponent.h>
Public Member Functions
void addBaseComponent (Own< AstComponentType > component)
add base components
void addClause (Own< AstClause > c)
add clause
void addComponent (Own< AstComponent > c)
add components
void addInstantiation (Own< AstComponentInit > i)
add instantiation
void addIO (Own< AstIO > directive)
add IO
void addOverride (const std::string &name)
add override
void addRelation (Own< AstRelation > r)
add relation
void addType (Own< AstType > t)
add type
void apply (const AstNodeMapper &mapper) override
Apply the mapper to all child nodes.
AstComponent * clone () const override
Create a clone (i.e.
void copyBaseComponents (const AstComponent &other)
copy base components
const std::vector< AstComponentType * > getBaseComponents () const
get base components
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< AstClause * > getClauses () const
get clauses
std::vector< AstComponent * > getComponents () const
get components
const AstComponentType * getComponentType () const
get component type
std::vector< AstComponentInit * > getInstantiations () const
get instantiation
std::vector< AstIO * > getIOs () const
get IO statements
const std::set< std::string > & getOverridden () const
get override
std::vector< AstRelation * > getRelations () const
get relations
std::vector< AstType * > getTypes () const
get types
void setComponentType (Own< AstComponentType > other)
set component type
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< AstComponentType > baseComponents
base components of component
VecOwn< AstClause > clauses
clauses
VecOwn< AstComponent > components
nested components
Own< AstComponentType > componentType
name of component and its formal component arguments.
VecOwn< AstComponentInit > instantiations
nested component instantiations.
VecOwn< AstIO > ios
I/O directives.
std::set< std::string > overrideRules
clauses of relations that are overwritten by this component
VecOwn< AstRelation > relations
relations
VecOwn< AstType > types
types declarations
Detailed Description
A AST node describing a component within the input program.
Definition at line 157 of file AstComponent.h.
Member Function Documentation
addBaseComponent()
void souffle::AstComponent::addBaseComponent (Own< AstComponentType > component) inline
add base components
Definition at line 175 of file AstComponent.h.
{
         baseComponents.push_back(std::move(component));
     }
addClause()
void souffle::AstComponent::addClause (Own< AstClause > c) inline
add clause
Definition at line 205 of file AstComponent.h.
References clauses.
{
         clauses.push_back(std::move(c));
     }
addComponent()
void souffle::AstComponent::addComponent (Own< AstComponent > c) inline
add components
Definition at line 225 of file AstComponent.h.
{
         components.push_back(std::move(c));
     }
addInstantiation()
void souffle::AstComponent::addInstantiation (Own< AstComponentInit > i) inline
add instantiation
Definition at line 235 of file AstComponent.h.
{
         instantiations.push_back(std::move(i));
     }
addIO()
void souffle::AstComponent::addIO (Own< AstIO > directive) inline
add IO
Definition at line 215 of file AstComponent.h.
References ios.
{
         ios.push_back(std::move(directive));
     }
addOverride()
void souffle::AstComponent::addOverride (const std::string & name) inline
add override
Definition at line 245 of file AstComponent.h.
{
         overrideRules.insert(name);
     }
addRelation()
void souffle::AstComponent::addRelation (Own< AstRelation > r) inline
add relation
Definition at line 195 of file AstComponent.h.
References relations.
{
         relations.push_back(std::move(r));
     }
addType()
void souffle::AstComponent::addType (Own< AstType > t) inline
add type
Definition at line 180 of file AstComponent.h.
References types.
{
         types.push_back(std::move(t));
     }
apply()
void souffle::AstComponent::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 268 of file AstComponent.h.
References clauses, ios, relations, and types.
{
         componentType = mapper(std::move(componentType));
         for (auto& cur : baseComponents) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : components) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : types) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : ios) {
             cur = mapper(std::move(cur));
         }
     }
clone()
AstComponent* souffle::AstComponent::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 254 of file AstComponent.h.
References clauses, souffle::clone(), ios, relations, and types.
{
         auto* res = new AstComponent();
         res->componentType = souffle::clone(componentType);
         res->baseComponents = souffle::clone(baseComponents);
         res->components = souffle::clone(components);
         res->instantiations = souffle::clone(instantiations);
         res->types = souffle::clone(types);
         res->relations = souffle::clone(relations);
         res->clauses = souffle::clone(clauses);
         res->ios = souffle::clone(ios);
         res->overrideRules = overrideRules;
         return res;
     }
copyBaseComponents()
void souffle::AstComponent::copyBaseComponents (const AstComponent & other) inline
copy base components
Definition at line 190 of file AstComponent.h.
References baseComponents, and souffle::clone().
{
         baseComponents = souffle::clone(other.baseComponents);
     }
equal()
bool souffle::AstComponent::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 341 of file AstComponent.h.
References clauses, souffle::equal_ptr(), souffle::equal_targets(), ios, relations, and types.
{
         const auto& other = static_cast<const AstComponent&>(node);
         if (equal_ptr(componentType, other.componentType)) {
             return true;
         }
         if (!equal_targets(baseComponents, other.baseComponents)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(ios, other.ios)) {
             return false;
         }
         if (overrideRules != other.overrideRules) {
             return false;
         }
         return true;
     }
getBaseComponents()
const std::vector<AstComponentType*> souffle::AstComponent::getBaseComponents () const inline
get base components
Definition at line 170 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(baseComponents);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstComponent::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 293 of file AstComponent.h.
References clauses, ios, relations, and types.
{
         std::vector<const AstNode*> res;
         res.push_back(componentType.get());
         for (const auto& cur : baseComponents) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : ios) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<AstClause*> souffle::AstComponent::getClauses () const inline
get clauses
Definition at line 210 of file AstComponent.h.
References clauses, and souffle::toPtrVector().
{
         return toPtrVector(clauses);
     }
getComponents()
std::vector<AstComponent*> souffle::AstComponent::getComponents () const inline
get components
Definition at line 230 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent(), souffle::ComponentLookup::getComponent(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getComponentType()
const AstComponentType* souffle::AstComponent::getComponentType () const inline
get component type
Definition at line 160 of file AstComponent.h.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return componentType.get();
     }
getInstantiations()
std::vector<AstComponentInit*> souffle::AstComponent::getInstantiations () const inline
get instantiation
Definition at line 240 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(instantiations);
     }
getIOs()
std::vector<AstIO*> souffle::AstComponent::getIOs () const inline
get IO statements
Definition at line 220 of file AstComponent.h.
References ios, and souffle::toPtrVector().
{
         return toPtrVector(ios);
     }
getOverridden()
const std::set<std::string>& souffle::AstComponent::getOverridden () const inline
get override
Definition at line 250 of file AstComponent.h.
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return overrideRules;
     }
getRelations()
std::vector<AstRelation*> souffle::AstComponent::getRelations () const inline
get relations
Definition at line 200 of file AstComponent.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(relations);
     }
getTypes()
std::vector<AstType*> souffle::AstComponent::getTypes () const inline
get types
Definition at line 185 of file AstComponent.h.
References souffle::toPtrVector(), and types.
{
         return toPtrVector(types);
     }
print()
void souffle::AstComponent::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 322 of file AstComponent.h.
References clauses, ios, souffle::join(), relations, and types.
{
         auto show = [&](auto&& xs, char const* sep = "\n", char const* prefix = "") {
             if (xs.empty()) return;
             os << prefix << join(xs, sep) << "\n";
         };
         os << ".comp " << *componentType << " ";
         show(baseComponents, ",", ": ");
         os << "{\n";
         show(components);
         show(instantiations);
         show(types);
         show(relations);
         show(overrideRules, ",", ".override ");
         show(clauses, "\n\n");
         show(ios, "\n\n");
         os << "}\n";
     }
setComponentType()
void souffle::AstComponent::setComponentType (Own< AstComponentType > other) inline
set component type
Definition at line 165 of file AstComponent.h.
{
         componentType = std::move(other);
     }
Field Documentation
baseComponents
VecOwn<AstComponentType> souffle::AstComponent::baseComponents protected
base components of component
Definition at line 378 of file AstComponent.h.
Referenced by copyBaseComponents().
clauses
VecOwn<AstClause> souffle::AstComponent::clauses protected
clauses
Definition at line 387 of file AstComponent.h.
components
VecOwn<AstComponent> souffle::AstComponent::components protected
nested components
Definition at line 393 of file AstComponent.h.
componentType
Own<AstComponentType> souffle::AstComponent::componentType protected
name of component and its formal component arguments.
Definition at line 375 of file AstComponent.h.
instantiations
VecOwn<AstComponentInit> souffle::AstComponent::instantiations protected
nested component instantiations.
Definition at line 396 of file AstComponent.h.
ios
VecOwn<AstIO> souffle::AstComponent::ios protected
I/O directives.
Definition at line 390 of file AstComponent.h.
overrideRules
std::set<std::string> souffle::AstComponent::overrideRules protected
clauses of relations that are overwritten by this component
Definition at line 399 of file AstComponent.h.
relations
VecOwn<AstRelation> souffle::AstComponent::relations protected
relations
Definition at line 384 of file AstComponent.h.
types
VecOwn<AstType> souffle::AstComponent::types protected
types declarations
Definition at line 381 of file AstComponent.h.
The documentation for this class was generated from the following file:
ast/AstComponent.h