souffle: souffle::ReadStreamJSON Class Reference
souffle::ReadStreamJSON Class Reference
#include <ReadStreamJSON.h>
Public Member Functions
ReadStreamJSON (std::istream &file, const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
Public Member Functions inherited from souffle::SerialisationStream< false >
virtual ~SerialisationStream ()=default
Protected Member Functions
RamDomain readNextElement (const Json &source, const std::string &recordTypeName)
std::unique_ptr< RamDomain[]> readNextTuple () override
Protected Member Functions inherited from souffle::ReadStream
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symTab, RecordTable &recTab)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Member Functions inherited from souffle::SerialisationStream< false >
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types, std::vector< std::string > relTypes, size_t auxArity=0)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, Json types)
SerialisationStream (RO< SymbolTable > &symTab, RO< RecordTable > &recTab, const std::map< std::string, std::string > &rwOperation)
Protected Attributes
std::istream & file
bool isInitialized
Json jsonSource
size_t pos
Protected Attributes inherited from souffle::SerialisationStream< false >
size_t arity
size_t auxiliaryArity
RO< RecordTable > & recordTable
RO< SymbolTable > & symbolTable
std::vector< std::string > typeAttributes
Json types
Additional Inherited Members
Protected Types inherited from souffle::SerialisationStream< false >
using RO = std::conditional_t< readOnlyTables, const A, A >
Detailed Description
Definition at line 42 of file ReadStreamJSON.h.
Constructor & Destructor Documentation
ReadStreamJSON()
souffle::ReadStreamJSON::ReadStreamJSON (std::istream & file, const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) inline
Definition at line 44 of file ReadStreamJSON.h.
             : ReadStream(rwOperation, symbolTable, recordTable), file(file), pos(0), isInitialized(false) {}
Member Function Documentation
readNextElement()
RamDomain souffle::ReadStreamJSON::readNextElement (const Json & source, const std::string & recordTypeName) inline protected
Definition at line 115 of file ReadStreamJSON.h.
References souffle::fatal(), i, json11::Json::int_value(), json11::Json::is_null(), json11::Json::number_value(), souffle::SerialisationStream< false >::recordTable, souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::types.
Referenced by readNextTuple().
{
         auto&& recordInfo = types["records"][recordTypeName];
         if (recordInfo.is_null()) {
             throw std::invalid_argument("Missing record type information: " + recordTypeName);
         }
         // Handle null case
         if (source.is_null()) {
             return 0;
         }
         auto&& recordTypes = recordInfo["types"];
         const size_t recordArity = recordInfo["arity"].long_value();
         std::vector<RamDomain> recordValues(recordArity);
         for (size_t i = 0; i < recordArity; ++i) {
             const std::string& recordType = recordTypes[i].string_value();
             switch (recordType[0]) {
                 case 's': {
                     recordValues[i] = symbolTable.unsafeLookup(source[i].string_value());
                     break;
                 }
                 case 'r': {
                     recordValues[i] = readNextElement(source[i], recordType);
                     break;
                 }
                 case 'i': {
                     recordValues[i] = source[i].int_value();
                     break;
                 }
                 case 'u': {
                     recordValues[i] = source[i].int_value();
                     break;
                 }
                 case 'f': {
                     recordValues[i] = source[i].number_value();
                     break;
                 }
                 default: fatal("invalid type attribute");
             }
         }
         return recordTable.pack(recordValues.data(), recordValues.size());
     }
readNextTuple()
std::unique_ptr<RamDomain[]> souffle::ReadStreamJSON::readNextTuple () inline override protected virtual
Implements souffle::ReadStream.
Definition at line 53 of file ReadStreamJSON.h.
References json11::Json::array_items(), souffle::fatal(), i, json11::Json::parse(), pos, readNextElement(), souffle::SerialisationStream< false >::symbolTable, and souffle::SerialisationStream< false >::typeAttributes.
{
         // for some reasons we cannot initalized our json objects in constructor
         // otherwise it will segfault, so we initialize in the first call
         if (!isInitialized) {
             isInitialized = true;
             std::string error = "";
             std::string source(std::istreambuf_iterator<char>(file), {});
             jsonSource = Json::parse(source, error);
             // it should be wrapped by an extra array
             if (error.length() > 0 || !jsonSource.is_array()) {
                 fatal("cannot deserialize json because %s:\n%s", error, source);
             }
         }
         if (pos >= jsonSource.array_items().size()) {
             return nullptr;
         }
         std::unique_ptr<RamDomain[]> tuple = std::make_unique<RamDomain[]>(typeAttributes.size());
         const Json& jsonObj = jsonSource[pos];
         pos++;
         for (size_t i = 0; i < typeAttributes.size(); ++i) {
             try {
                 auto&& ty = typeAttributes.at(i);
                 switch (ty[0]) {
                     case 's': {
                         tuple[i] = symbolTable.unsafeLookup(jsonObj[i].string_value());
                         break;
                     }
                     case 'r': {
                         tuple[i] = readNextElement(jsonObj[i], ty);
                         break;
                     }
                     case 'i': {
                         tuple[i] = jsonObj[i].int_value();
                         break;
                     }
                     case 'u': {
                         tuple[i] = jsonObj[i].int_value();
                         break;
                     }
                     case 'f': {
                         tuple[i] = jsonObj[i].number_value();
                         break;
                     }
                     default: fatal("invalid type attribute: `%c`", ty[0]);
                 }
             } catch (...) {
                 std::stringstream errorMessage;
                 if (jsonObj.is_array() && i < jsonObj.array_items().size()) {
                     errorMessage << "Error converting: " << jsonObj[i].dump();
                 } else {
                     errorMessage << "Invalid index: " << i;
                 }
                 throw std::invalid_argument(errorMessage.str());
             }
         }
         return tuple;
     }
Field Documentation
file
std::istream& souffle::ReadStreamJSON::file protected
Definition at line 49 of file ReadStreamJSON.h.
isInitialized
bool souffle::ReadStreamJSON::isInitialized protected
Definition at line 52 of file ReadStreamJSON.h.
jsonSource
Json souffle::ReadStreamJSON::jsonSource protected
Definition at line 51 of file ReadStreamJSON.h.
pos
size_t souffle::ReadStreamJSON::pos protected
Definition at line 50 of file ReadStreamJSON.h.
Referenced by readNextTuple().
The documentation for this class was generated from the following file:
ReadStreamJSON.h