souffle: souffle::RelationSchedule Class Reference
souffle::RelationSchedule Class Reference
Analysis pass computing a schedule for computing relations.
#include <PrecedenceGraph.h>
Public Member Functions
void print (std::ostream &os) const override
Dump this relation schedule to standard error.
RelationSchedule ()
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
const std::vector< RelationScheduleStep > & schedule () const
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "relation-schedule"
Private Member Functions
std::vector< std::set< const AstRelation * > > computeRelationExpirySchedule (const AstTranslationUnit &translationUnit)
Private Attributes
PrecedenceGraph * precedenceGraph = nullptr
std::vector< RelationScheduleStep > relationSchedule
Relations computed and expired relations at each step.
TopologicallySortedSCCGraph * topsortSCCGraph = nullptr
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass computing a schedule for computing relations.
Definition at line 432 of file PrecedenceGraph.h.
Constructor & Destructor Documentation
RelationSchedule()
souffle::RelationSchedule::RelationSchedule () inline
Definition at line 436 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::run().
 : AstAnalysis(name) {}
Member Function Documentation
computeRelationExpirySchedule()
std::vector< std::set< const AstRelation * > > souffle::RelationSchedule::computeRelationExpirySchedule (const AstTranslationUnit & translationUnit) private
Definition at line 567 of file PrecedenceGraph.cpp.
References souffle::AstTranslationUnit::getAnalysis().
{
     std::vector<std::set<const AstRelation*>> relationExpirySchedule;
     /* Compute for each step in the reverse topological order
        of evaluating the SCC the set of alive relations. */
     size_t numSCCs = topsortSCCGraph->order().size();
     /* Alive set for each step */
     std::vector<std::set<const AstRelation*>> alive(numSCCs);
     /* Resize expired relations sets */
     relationExpirySchedule.resize(numSCCs);
     const auto& sccGraph = translationUnit.getAnalysis<SCCGraph>();
     /* Compute all alive relations by iterating over all steps in reverse order
        determine the dependencies */
     for (size_t orderedSCC = 1; orderedSCC < numSCCs; orderedSCC++) {
         /* Add alive set of previous step */
         alive[orderedSCC].insert(alive[orderedSCC - 1].begin(), alive[orderedSCC - 1].end());
         /* Add predecessors of relations computed in this step */
         auto scc = topsortSCCGraph->order()[numSCCs - orderedSCC];
         for (const AstRelation* r : sccGraph->getInternalRelations(scc)) {
             for (const AstRelation* predecessor : precedenceGraph->graph().predecessors(r)) {
                 alive[orderedSCC].insert(predecessor);
             }
         }
         /* Compute expired relations in reverse topological order using the set difference of the alive sets
            between steps. */
         std::set_difference(alive[orderedSCC].begin(), alive[orderedSCC].end(), alive[orderedSCC - 1].begin(),
                 alive[orderedSCC - 1].end(),
                 std::inserter(relationExpirySchedule[numSCCs - orderedSCC],
                         relationExpirySchedule[numSCCs - orderedSCC].end()));
     }
     return relationExpirySchedule;
 }
print()
void souffle::RelationSchedule::print (std::ostream & os) const override virtual
Dump this relation schedule to standard error.
Reimplemented from souffle::AstAnalysis.
Definition at line 605 of file PrecedenceGraph.cpp.
{
     os << "begin schedule\n";
     for (const RelationScheduleStep& step : relationSchedule) {
         os << step;
         os << "computed: ";
         for (const AstRelation* compRel : step.computed()) {
             os << compRel->getQualifiedName() << ", ";
         }
         os << "\nexpired: ";
         for (const AstRelation* compRel : step.expired()) {
             os << compRel->getQualifiedName() << ", ";
         }
         os << "\n";
         if (step.recursive()) {
             os << "recursive";
         } else {
             os << "not recursive";
         }
         os << "\n";
     }
     os << "end schedule\n";
 }
run()
void souffle::RelationSchedule::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 549 of file PrecedenceGraph.cpp.
References souffle::AstTranslationUnit::getAnalysis(), i, and souffle::SCCGraph::isRecursive().
{
     topsortSCCGraph = translationUnit.getAnalysis<TopologicallySortedSCCGraph>();
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraph>();
     size_t numSCCs = translationUnit.getAnalysis<SCCGraph>()->getNumberOfSCCs();
     std::vector<std::set<const AstRelation*>> relationExpirySchedule =
             computeRelationExpirySchedule(translationUnit);
     relationSchedule.clear();
     for (size_t i = 0; i < numSCCs; i++) {
         auto scc = topsortSCCGraph->order()[i];
         const std::set<const AstRelation*> computedRelations =
                 translationUnit.getAnalysis<SCCGraph>()->getInternalRelations(scc);
         relationSchedule.emplace_back(computedRelations, relationExpirySchedule[i],
                 translationUnit.getAnalysis<SCCGraph>()->isRecursive(scc));
     }
 }
schedule()
const std::vector<RelationScheduleStep>& souffle::RelationSchedule::schedule () const inline
Definition at line 440 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::print().
{
         return relationSchedule;
     }
Field Documentation
name
constexpr const char* souffle::RelationSchedule::name = "relation-schedule" static
Definition at line 434 of file PrecedenceGraph.h.
precedenceGraph
PrecedenceGraph* souffle::RelationSchedule::precedenceGraph = nullptr private
Definition at line 449 of file PrecedenceGraph.h.
relationSchedule
std::vector<RelationScheduleStep> souffle::RelationSchedule::relationSchedule private
Relations computed and expired relations at each step.
Definition at line 452 of file PrecedenceGraph.h.
topsortSCCGraph
TopologicallySortedSCCGraph* souffle::RelationSchedule::topsortSCCGraph = nullptr private
Definition at line 448 of file PrecedenceGraph.h.
The documentation for this class was generated from the following files:
ast/analysis/PrecedenceGraph.h
ast/analysis/PrecedenceGraph.cpp