souffle: souffle::SCCGraph Class Reference
souffle::SCCGraph Class Reference
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
#include <PrecedenceGraph.h>
Public Member Functions
std::set< const AstRelation * > getExternalNonOutputPredecessorRelations (const size_t scc) const
Get all external non-output predecessor relations of a given SCC.
std::set< const AstRelation * > getExternalOutputPredecessorRelations (const size_t scc) const
Get all external output predecessor relations of a given SCC.
std::set< const AstRelation * > getExternalPredecessorRelations (const size_t scc) const
Get all external predecessor relations of a given SCC.
std::set< const AstRelation * > getInternalInputRelations (const size_t scc) const
Get all internal input relations of a given SCC.
std::set< const AstRelation * > getInternalNonOutputRelationsWithExternalSuccessors (const size_t scc) const
Get all internal non-output relations of a given SCC with external successors.
std::set< const AstRelation * > getInternalOutputRelations (const size_t scc) const
Get all internal output relations of a given SCC.
const std::set< const AstRelation * > & getInternalRelations (const size_t scc) const
Get all internal relations of a given SCC.
std::set< const AstRelation * > getInternalRelationsWithExternalSuccessors (const size_t scc) const
Get all internal relations of a given SCC with external successors.
size_t getNumberOfSCCs () const
Get the number of SCCs in the graph.
const std::set< size_t > & getPredecessorSCCs (const size_t scc) const
Get all predecessor SCCs of a given SCC.
std::set< size_t > getPredecessorSCCs (const AstRelation *relation) const
Get all SCCs containing a predecessor of a given relation.
size_t getSCC (const AstRelation *rel) const
Get the SCC of the given relation.
const std::set< size_t > & getSuccessorSCCs (const size_t scc) const
Get all successor SCCs of a given SCC.
std::set< size_t > getSuccessorSCCs (const AstRelation *relation) const
Get all SCCs containing a successor of a given relation.
bool isRecursive (const size_t scc) const
Return if the given SCC is recursive.
void print (std::ostream &os) const override
Print the SCC graph.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
SCCGraph ()
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "scc-graph"
Private Member Functions
void scR (const AstRelation *relation, std::map< const AstRelation *, size_t > &preOrder, size_t &counter, std::stack< const AstRelation *> &S, std::stack< const AstRelation *> &P, size_t &numSCCs)
Recursive scR method for computing SCC.
Private Attributes
IOType * ioType = nullptr
PrecedenceGraph * precedenceGraph = nullptr
std::vector< std::set< size_t > > predecessors
Predecessor set for the SCC graph.
std::map< const AstRelation *, size_t > relationToScc
Map from node number to SCC number.
std::vector< std::set< const AstRelation * > > sccToRelation
Relations contained in a SCC.
std::vector< std::set< size_t > > successors
Adjacency lists for the SCC graph.
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
Definition at line 154 of file PrecedenceGraph.h.
Constructor & Destructor Documentation
SCCGraph()
souffle::SCCGraph::SCCGraph () inline
Definition at line 158 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::run().
 : AstAnalysis(name) {}
Member Function Documentation
getExternalNonOutputPredecessorRelations()
std::set<const AstRelation*> souffle::SCCGraph::getExternalNonOutputPredecessorRelations (const size_t scc) const inline
Get all external non-output predecessor relations of a given SCC.
Definition at line 227 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> externNonOutPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc && !ioType->isOutput(predecessor)) {
                     externNonOutPreds.insert(predecessor);
                 }
             }
         }
         return externNonOutPreds;
     }
getExternalOutputPredecessorRelations()
std::set<const AstRelation*> souffle::SCCGraph::getExternalOutputPredecessorRelations (const size_t scc) const inline
Get all external output predecessor relations of a given SCC.
Definition at line 214 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> externOutPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc && ioType->isOutput(predecessor)) {
                     externOutPreds.insert(predecessor);
                 }
             }
         }
         return externOutPreds;
     }
getExternalPredecessorRelations()
std::set<const AstRelation*> souffle::SCCGraph::getExternalPredecessorRelations (const size_t scc) const inline
Get all external predecessor relations of a given SCC.
Definition at line 240 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> externPreds;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
                 if (relationToScc.at(predecessor) != scc) {
                     externPreds.insert(predecessor);
                 }
             }
         }
         return externPreds;
     }
getInternalInputRelations()
std::set<const AstRelation*> souffle::SCCGraph::getInternalInputRelations (const size_t scc) const inline
Get all internal input relations of a given SCC.
Definition at line 294 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> internIns;
         for (const auto& relation : getInternalRelations(scc)) {
             if (ioType->isInput(relation)) {
                 internIns.insert(relation);
             }
         }
         return internIns;
     }
getInternalNonOutputRelationsWithExternalSuccessors()
std::set<const AstRelation*> souffle::SCCGraph::getInternalNonOutputRelationsWithExternalSuccessors (const size_t scc) const inline
Get all internal non-output relations of a given SCC with external successors.
Definition at line 278 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> internNonOutsWithExternSuccs;
         for (const auto& relation : getInternalRelations(scc)) {
             if (!ioType->isOutput(relation)) {
                 for (const auto& successor : precedenceGraph->graph().successors(relation)) {
                     if (relationToScc.at(successor) != scc) {
                         internNonOutsWithExternSuccs.insert(relation);
                         break;
                     }
                 }
             }
         }
         return internNonOutsWithExternSuccs;
     }
getInternalOutputRelations()
std::set<const AstRelation*> souffle::SCCGraph::getInternalOutputRelations (const size_t scc) const inline
Get all internal output relations of a given SCC.
Definition at line 253 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> internOuts;
         for (const auto& relation : getInternalRelations(scc)) {
             if (ioType->isOutput(relation)) {
                 internOuts.insert(relation);
             }
         }
         return internOuts;
     }
getInternalRelations()
const std::set<const AstRelation*>& souffle::SCCGraph::getInternalRelations (const size_t scc) const inline
Get all internal relations of a given SCC.
Definition at line 209 of file PrecedenceGraph.h.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl().
{
         return sccToRelation.at(scc);
     }
getInternalRelationsWithExternalSuccessors()
std::set<const AstRelation*> souffle::SCCGraph::getInternalRelationsWithExternalSuccessors (const size_t scc) const inline
Get all internal relations of a given SCC with external successors.
Definition at line 264 of file PrecedenceGraph.h.
References relation.
{
         std::set<const AstRelation*> internsWithExternSuccs;
         for (const auto& relation : getInternalRelations(scc)) {
             for (const auto& successor : precedenceGraph->graph().successors(relation)) {
                 if (relationToScc.at(successor) != scc) {
                     internsWithExternSuccs.insert(relation);
                     break;
                 }
             }
         }
         return internsWithExternSuccs;
     }
getNumberOfSCCs()
size_t souffle::SCCGraph::getNumberOfSCCs () const inline
Get the number of SCCs in the graph.
Definition at line 163 of file PrecedenceGraph.h.
{
         return sccToRelation.size();
     }
getPredecessorSCCs() [1/2]
const std::set<size_t>& souffle::SCCGraph::getPredecessorSCCs (const size_t scc) const inline
Get all predecessor SCCs of a given SCC.
Definition at line 178 of file PrecedenceGraph.h.
{
         return predecessors.at(scc);
     }
getPredecessorSCCs() [2/2]
std::set<size_t> souffle::SCCGraph::getPredecessorSCCs (const AstRelation * relation) const inline
Get all SCCs containing a predecessor of a given relation.
Definition at line 196 of file PrecedenceGraph.h.
{
         std::set<size_t> predecessorSccs;
         const auto scc = relationToScc.at(relation);
         for (const auto& predecessor : precedenceGraph->graph().predecessors(relation)) {
             const auto predecessorScc = relationToScc.at(predecessor);
             if (predecessorScc != scc) {
                 predecessorSccs.insert(predecessorScc);
             }
         }
         return predecessorSccs;
     }
getSCC()
size_t souffle::SCCGraph::getSCC (const AstRelation * rel) const inline
Get the SCC of the given relation.
Definition at line 168 of file PrecedenceGraph.h.
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl().
{
         return relationToScc.at(rel);
     }
getSuccessorSCCs() [1/2]
const std::set<size_t>& souffle::SCCGraph::getSuccessorSCCs (const size_t scc) const inline
Get all successor SCCs of a given SCC.
Definition at line 173 of file PrecedenceGraph.h.
{
         return successors.at(scc);
     }
getSuccessorSCCs() [2/2]
std::set<size_t> souffle::SCCGraph::getSuccessorSCCs (const AstRelation * relation) const inline
Get all SCCs containing a successor of a given relation.
Definition at line 183 of file PrecedenceGraph.h.
{
         std::set<size_t> successorSccs;
         const auto scc = relationToScc.at(relation);
         for (const auto& successor : precedenceGraph->graph().successors(relation)) {
             const auto successorScc = relationToScc.at(successor);
             if (successorScc != scc) {
                 successorSccs.insert(successorScc);
             }
         }
         return successorSccs;
     }
isRecursive()
bool souffle::SCCGraph::isRecursive (const size_t scc) const inline
Return if the given SCC is recursive.
Definition at line 305 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::print().
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), and souffle::RelationSchedule::run().
{
         const std::set<const AstRelation*>& sccRelations = sccToRelation.at(scc);
         if (sccRelations.size() == 1) {
             const AstRelation* singleRelation = *sccRelations.begin();
             if (precedenceGraph->graph().predecessors(singleRelation).count(singleRelation) == 0u) {
                 return false;
             }
         }
         return true;
     }
print()
void souffle::SCCGraph::print (std::ostream & os) const override virtual
Print the SCC graph.
Reimplemented from souffle::AstAnalysis.
Definition at line 365 of file PrecedenceGraph.cpp.
References souffle::Global::config(), souffle::AstAnalysis::getName(), souffle::AstRelation::getQualifiedName(), souffle::join(), souffle::PrecedenceGraph::name, and souffle::profile::ss.
{
     const std::string& name = Global::config().get("name");
     std::stringstream ss;
     /* Print SCC graph */
     ss << "digraph {" << std::endl;
     /* Print nodes of SCC graph */
     for (size_t scc = 0; scc < getNumberOfSCCs(); scc++) {
         ss << "\t" << name << "_" << scc << "[label = \"";
         ss << join(getInternalRelations(scc), ",\\n",
                 [](std::ostream& out, const AstRelation* rel) { out << rel->getQualifiedName(); });
         ss << "\" ];" << std::endl;
     }
     for (size_t scc = 0; scc < getNumberOfSCCs(); scc++) {
         for (auto succ : getSuccessorSCCs(scc)) {
             ss << "\t" << name << "_" << scc << " -> " << name << "_" << succ << ";" << std::endl;
         }
     }
     ss << "}";
     printHTMLGraph(os, ss.str(), getName());
 }
run()
void souffle::SCCGraph::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 286 of file PrecedenceGraph.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), relation, relations, and S.
{
     precedenceGraph = translationUnit.getAnalysis<PrecedenceGraph>();
     ioType = translationUnit.getAnalysis<IOType>();
     sccToRelation.clear();
     relationToScc.clear();
     predecessors.clear();
     successors.clear();
     /* Compute SCC */
     std::vector<AstRelation*> relations = translationUnit.getProgram()->getRelations();
     size_t counter = 0;
     size_t numSCCs = 0;
     std::stack<const AstRelation*> S;
     std::stack<const AstRelation*> P;
     std::map<const AstRelation*, size_t> preOrder;  // Pre-order number of a node (for Gabow's Algo)
     for (const AstRelation* relation : relations) {
         relationToScc[relation] = preOrder[relation] = (size_t)-1;
     }
     for (const AstRelation* relation : relations) {
         if (preOrder[relation] == (size_t)-1) {
             scR(relation, preOrder, counter, S, P, numSCCs);
         }
     }
     /* Build SCC graph */
     successors.resize(numSCCs);
     predecessors.resize(numSCCs);
     for (const AstRelation* u : relations) {
         for (const AstRelation* v : precedenceGraph->graph().predecessors(u)) {
             auto scc_u = relationToScc[u];
             auto scc_v = relationToScc[v];
             assert(scc_u < numSCCs && "Wrong range");
             assert(scc_v < numSCCs && "Wrong range");
             if (scc_u != scc_v) {
                 predecessors[scc_u].insert(scc_v);
                 successors[scc_v].insert(scc_u);
             }
         }
     }
     /* Store the relations for each SCC */
     sccToRelation.resize(numSCCs);
     for (const AstRelation* relation : relations) {
         sccToRelation[relationToScc[relation]].insert(relation);
     }
 }
scR()
void souffle::SCCGraph::scR (const AstRelation * relation, std::map< const AstRelation *, size_t > & preOrder, size_t & counter, std::stack< const AstRelation *> & S, std::stack< const AstRelation *> & P, size_t & numSCCs) private
Recursive scR method for computing SCC.
Definition at line 336 of file PrecedenceGraph.cpp.
{
     preOrder[w] = counter++;
     S.push(w);
     P.push(w);
     for (const AstRelation* t : precedenceGraph->graph().predecessors(w)) {
         if (preOrder[t] == (size_t)-1) {
             scR(t, preOrder, counter, S, P, numSCCs);
         } else if (relationToScc[t] == (size_t)-1) {
             while (preOrder[P.top()] > preOrder[t]) {
                 P.pop();
             }
         }
     }
     if (P.top() == w) {
         P.pop();
     } else {
         return;
     }
     const AstRelation* v;
     do {
         v = S.top();
         S.pop();
         relationToScc[v] = numSCCs;
     } while (v != w);
     numSCCs++;
 }
Field Documentation
ioType
IOType* souffle::SCCGraph::ioType = nullptr private
Definition at line 338 of file PrecedenceGraph.h.
name
constexpr const char* souffle::SCCGraph::name = "scc-graph" static
Definition at line 156 of file PrecedenceGraph.h.
precedenceGraph
PrecedenceGraph* souffle::SCCGraph::precedenceGraph = nullptr private
Definition at line 320 of file PrecedenceGraph.h.
predecessors
std::vector<std::set<size_t> > souffle::SCCGraph::predecessors private
Predecessor set for the SCC graph.
Definition at line 329 of file PrecedenceGraph.h.
relationToScc
std::map<const AstRelation*, size_t> souffle::SCCGraph::relationToScc private
Map from node number to SCC number.
Definition at line 323 of file PrecedenceGraph.h.
sccToRelation
std::vector<std::set<const AstRelation*> > souffle::SCCGraph::sccToRelation private
Relations contained in a SCC.
Definition at line 332 of file PrecedenceGraph.h.
successors
std::vector<std::set<size_t> > souffle::SCCGraph::successors private
Adjacency lists for the SCC graph.
Definition at line 326 of file PrecedenceGraph.h.
The documentation for this class was generated from the following files:
ast/analysis/PrecedenceGraph.h
ast/analysis/PrecedenceGraph.cpp