souffle: souffle::RelationDetailCache Class Reference
souffle::RelationDetailCache Class Reference
Analysis pass mapping identifiers with relations and clauses.
#include <PrecedenceGraph.h>
Public Member Functions
std::set< AstClause * > getClauses (const AstRelation *rel) const
std::set< AstClause * > getClauses (const AstQualifiedName &name) const
AstRelation * getRelation (const AstQualifiedName &name) const
void print (std::ostream &os) const override
print the analysis result in HTML format
RelationDetailCache ()
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "relation-detail"
Private Attributes
std::map< AstQualifiedName, std::set< AstClause * > > nameToClauses
std::map< AstQualifiedName, AstRelation * > nameToRelation
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Analysis pass mapping identifiers with relations and clauses.
Definition at line 117 of file PrecedenceGraph.h.
Constructor & Destructor Documentation
RelationDetailCache()
souffle::RelationDetailCache::RelationDetailCache () inline
Definition at line 121 of file PrecedenceGraph.h.
References souffle::PrecedenceGraph::print(), and souffle::PrecedenceGraph::run().
 : AstAnalysis(name) {}
Member Function Documentation
getClauses() [1/2]
std::set<AstClause*> souffle::RelationDetailCache::getClauses (const AstRelation * rel) const inline
Definition at line 134 of file PrecedenceGraph.h.
References souffle::getClauses(), and souffle::AstRelation::getQualifiedName().
{
         assert(rel != nullptr && "invalid relation");
         return getClauses(rel->getQualifiedName());
     }
getClauses() [2/2]
std::set<AstClause*> souffle::RelationDetailCache::getClauses (const AstQualifiedName & name) const inline
Definition at line 139 of file PrecedenceGraph.h.
{
         if (nameToClauses.find(name) != nameToClauses.end()) {
             return nameToClauses.at(name);
         }
         return std::set<AstClause*>();
     }
getRelation()
AstRelation* souffle::RelationDetailCache::getRelation (const AstQualifiedName & name) const inline
Definition at line 127 of file PrecedenceGraph.h.
Referenced by souffle::getGroundedTerms().
{
         if (nameToRelation.find(name) != nameToRelation.end()) {
             return nameToRelation.at(name);
         }
         return nullptr;
     }
print()
void souffle::RelationDetailCache::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 211 of file PrecedenceGraph.cpp.
{
     for (const auto& pair : nameToClauses) {
         os << "--" << pair.first << "--";
         os << std::endl;
         for (const auto* clause : pair.second) {
             os << *clause << std::endl;
         }
         os << std::endl;
     }
 }
run()
void souffle::RelationDetailCache::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 196 of file PrecedenceGraph.cpp.
References souffle::AstTranslationUnit::getProgram().
{
     const auto& program = *translationUnit.getProgram();
     for (auto* rel : program.getRelations()) {
         nameToRelation[rel->getQualifiedName()] = rel;
         nameToClauses[rel->getQualifiedName()] = std::set<AstClause*>();
     }
     for (auto* clause : program.getClauses()) {
         const auto& relationName = clause->getHead()->getQualifiedName();
         if (nameToClauses.find(relationName) == nameToClauses.end()) {
             nameToClauses[relationName] = std::set<AstClause*>();
         }
         nameToClauses.at(relationName).insert(clause);
     }
 }
Field Documentation
name
constexpr const char* souffle::RelationDetailCache::name = "relation-detail" static
Definition at line 119 of file PrecedenceGraph.h.
nameToClauses
std::map<AstQualifiedName, std::set<AstClause*> > souffle::RelationDetailCache::nameToClauses private
Definition at line 148 of file PrecedenceGraph.h.
nameToRelation
std::map<AstQualifiedName, AstRelation*> souffle::RelationDetailCache::nameToRelation private
Definition at line 147 of file PrecedenceGraph.h.
The documentation for this class was generated from the following files:
ast/analysis/PrecedenceGraph.h
ast/analysis/PrecedenceGraph.cpp