souffle: souffle::AuxiliaryArity Class Reference
souffle::AuxiliaryArity Class Reference
Determine the auxiliary arity for relations.
#include <AuxArityAnalysis.h>
Public Member Functions
AuxiliaryArity ()
size_t getArity (const AstAtom *atom) const
Returns the number of auxiliary parameters of an atom's relation.
size_t getArity (const AstRelation *relation) const
Returns the number of auxiliary parameters of a relation.
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual void print (std::ostream &) const
print the analysis result in HTML format
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "auxiliary-arity"
Private Member Functions
size_t computeArity (const AstRelation *relation) const
Returns the number of auxiliary parameters of a relation.
Private Attributes
const AstProgram * program = nullptr
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Determine the auxiliary arity for relations.
Definition at line 33 of file AuxArityAnalysis.h.
Constructor & Destructor Documentation
AuxiliaryArity()
souffle::AuxiliaryArity::AuxiliaryArity () inline
Definition at line 37 of file AuxArityAnalysis.h.
 : AstAnalysis(name) {}
Member Function Documentation
computeArity()
size_t souffle::AuxiliaryArity::computeArity (const AstRelation * relation) const private
Returns the number of auxiliary parameters of a relation.
Parameters
relation the relation to report on
Returns
number of auxiliary attributes
Definition at line 27 of file AuxArityAnalysis.cpp.
References souffle::Global::config(), souffle::getClauses(), and program.
Referenced by getArity().
{
     if (Global::config().has("provenance")) {
         if (Global::config().get("provenance") == "subtreeHeights") {
             size_t maxNrOfPremises = 0;
             for (auto& cur : getClauses(*program, *relation)) {
                 size_t numberOfAtoms = getBodyLiterals<AstAtom>(*cur).size();
                 if (numberOfAtoms > maxNrOfPremises) {
                     maxNrOfPremises = numberOfAtoms;
                 }
             }
             return maxNrOfPremises + 2;
         }
         return 2;
     } else {
         return 0;
     }
 }
getArity() [1/2]
size_t souffle::AuxiliaryArity::getArity (const AstAtom * atom) const inline
Returns the number of auxiliary parameters of an atom's relation.
Parameters
atom the atom to report on
Returns
number of auxiliary attributes
Definition at line 48 of file AuxArityAnalysis.h.
References computeArity(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), and program.
Referenced by souffle::AstTranslator::getEvaluationArity(), souffle::AstTranslator::makeNegationSubproofSubroutine(), souffle::AstTranslator::makeSubproofSubroutine(), and souffle::AstTranslator::translateProgram().
{
         return computeArity(getRelation(*program, atom->getQualifiedName()));
     }
getArity() [2/2]
size_t souffle::AuxiliaryArity::getArity (const AstRelation * relation) const inline
Returns the number of auxiliary parameters of a relation.
Parameters
relation the relation to report on
Returns
number of auxiliary attributes
Definition at line 57 of file AuxArityAnalysis.h.
References computeArity(), and relation.
{
         return computeArity(relation);
     }
run()
void souffle::AuxiliaryArity::run (const AstTranslationUnit &) inline override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 39 of file AuxArityAnalysis.h.
References souffle::AstTranslationUnit::getProgram(), and program.
{
         program = translationUnit.getProgram();
     }
Field Documentation
name
constexpr const char* souffle::AuxiliaryArity::name = "auxiliary-arity" static
Definition at line 35 of file AuxArityAnalysis.h.
program
const AstProgram* souffle::AuxiliaryArity::program = nullptr private
Definition at line 69 of file AuxArityAnalysis.h.
Referenced by computeArity(), getArity(), and run().
The documentation for this class was generated from the following files:
ast/analysis/AuxArityAnalysis.h
ast/analysis/AuxArityAnalysis.cpp